package component:component-features;

interface shift-manager {

    enum shift-time {
        morning,
        afternoon
    }

    enum shift-weekday {
        mon,
        tue,
        wed,
        thu,
        fri,
        sat,
        sun,
    }

    // スタッフグループ
    record staff-group {
        name: string,
        slots: list<staff-info>,
    }

    record staff-info {
        name: string,
    }

    // 週ごとのルールデータ
    record weekly-rule {
        name: string,
        schedule: week-schedule
    }

    record week-schedule {
        mon: day-shift-ids,
        tue: day-shift-ids,
        wed: day-shift-ids,
        thu: day-shift-ids,
        fri: day-shift-ids,
        sat: day-shift-ids,
        sun: day-shift-ids,
    }

    record day-shift-ids {
        m: list<holl>,
        a: list<holl>,
    }

    record holl {
        staff-group-id:u32,    // スタッフグループを指す
        shift-staff-index:u32, // シフトのルールを司るindex
    }

    // 出力データ

    record staff-pill {
        name: string,
        staff-group-id:u32,
        staff-index: u32,
    }

    record daily-shift {
        date: string, // "2026-01-08"
        has-data: bool, // データが存在するか (skipなどでないか)
        m: list<staff-pill>,  // 午前
        a: list<staff-pill>,  // 午後
    }

    resource shift-manager {
        constructor();

        // 新しいスタッフグループを追加
        add-new-group: func();

        // スタッフグループを削除
        remove-group: func(index: u32);

        // スタッフグループの名前を更新
        update-group-name: func(index: u32, name: string);

        // 引数で指定されたグループに
        // 具体的なスタッフを格納するスロットを追加
        add-slot: func(group-idx: u32);

        // 引数で指定されたグループのスロットを削除
        remove-slot: func(group-idx: u32, slot-idx: u32);

        // スタッフの名前の変更
        update-slot-memo: func(group-idx: u32, slot-idx: u32, memo: string);

        // 新しいweekly ruleを追加
        add-rule: func();

        // weekly ruleを削除
        remove-rule: func(index: u32);

        // weekly ruleの名称変更
        update-rule-name: func(index: u32, name: string);

        // weekly ruleに新しいシフトホールを追加する
        add-rule-assignment: func(
            rule-idx: u32,  //
            day: shift-weekday,    // mon - sun
            shift-time: shift-time,  // morning afternoon
            staff-group-id: u32, // assignされうるstaff groupのindex
            shift-staff-index: u32,// ホール
        );

        // weekly ruleから指定されたホールを削除する
        remove-rule-assignment: func(
            rule-idx: u32,  //
            day: shift-weekday,    // mon - sun
            shift-time: shift-time,  // morning afternoon
            index: u32, 
        );

        get-rule-assignment: func(
            rule-idx: u32,  //
            day: shift-weekday,    // mon - sun
            shift-time: shift-time,  // morning afternoon
        ) -> option<list<holl>>;

        // 前の月
        change-prev-month: func();

        // 次の月
        change-next-month: func();

        get-rules: func() -> list<weekly-rule>;

        get-staff-groups: func() -> list<staff-group>;

        // year
        get-year: func() -> u32;

        // month
        get-month: func() -> u32;
    }
}

world shift-manager-world {
    export shift-manager;
}

world shift-gen-world {
	import dummy:logger/logger@0.1.0-alpha;
    import config-mock:config-mock/config-mock@0.1.0-alpha;

    export to-upper: func(input: string) -> string;
    export calculate-weeks-delta-from-base: func(year: s32, month: u32, day: u32) -> option<s64>;
}
